FROM eyedeekay/coreboot-dockerfile
COPY vendor/alienware /home/coreboot/coreboot/src/mainboard/alienware
COPY .config /home/coreboot/coreboot
RUN make build/config.h
ENTRYPOINT [ "bash", "-i", "-c" ]
