FROM eyedeekay/coreboot-dockerfile
USER coreboot
COPY vendor/alienware /home/coreboot/coreboot/src/mainboard/alienware
COPY vendor/dell /home/coreboot/coreboot/src/mainboard/dell
COPY vendor/acer /home/coreboot/coreboot/src/mainboard/acer
COPY .config /home/coreboot/coreboot
RUN make oldconfig
ENTRYPOINT [ "bash", "-i", "-c" ]
